package com.github.tentac.swagger2md.core;

import com.github.tentac.swagger2md.model.EndpointInfo;
import com.github.tentac.swagger2md.model.ParameterInfo;

import java.util.List;

/**
 * Formats API endpoint metadata into structured Markdown.
 */
public class MarkdownFormatter {

    private static final String SECTION_SEPARATOR = "\n\n---\n\n";

    /**
     * Format a list of endpoints grouped by tags into Markdown.
     *
     * @param title       the API title
     * @param description the API description
     * @param version     the API version
     * @param endpoints   all endpoints
     * @return formatted Markdown string
     */
    public String format(String title, String description, String version, List<EndpointInfo> endpoints) {
        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("# ").append(title != null ? title : "API Documentation").append("\n\n");

        if (description != null && !description.isEmpty()) {
            sb.append("> ").append(description).append("\n\n");
        }

        sb.append("**Version:** ").append(version != null ? version : "1.0.0").append("\n\n");

        // Table of Contents
        sb.append("## Table of Contents\n\n");
        List<String> tags = endpoints.stream()
                .flatMap(e -> e.getTags().stream())
                .distinct()
                .toList();

        for (int i = 0; i < tags.size(); i++) {
            sb.append(i + 1).append(". [").append(tags.get(i)).append("](#").append(toAnchor(tags.get(i))).append(")\n");
        }
        sb.append("\n");

        // Group endpoints by tags and format
        for (String tag : tags) {
            sb.append(SECTION_SEPARATOR);
            sb.append("## ").append(tag).append(" {#").append(toAnchor(tag)).append("}\n\n");

            List<EndpointInfo> taggedEndpoints = endpoints.stream()
                    .filter(e -> e.getTags().contains(tag))
                    .toList();

            for (int i = 0; i < taggedEndpoints.size(); i++) {
                EndpointInfo endpoint = taggedEndpoints.get(i);
                formatEndpoint(sb, endpoint);
                if (i < taggedEndpoints.size() - 1) {
                    sb.append("\n\n---\n");
                }
            }
        }

        // Footer
        sb.append("\n\n---\n\n");
        sb.append("*Generated by Swagger2md - Markdown API Documentation*\n");

        return sb.toString();
    }

    private void formatEndpoint(StringBuilder sb, EndpointInfo endpoint) {
        // Endpoint header
        sb.append("\n### ");

        // Badge-style HTTP method
        sb.append("`").append(endpoint.getHttpMethod()).append("` ");
        sb.append(endpoint.getPath());

        if (endpoint.isDeprecated()) {
            sb.append(" *(deprecated)*");
        }
        sb.append("\n\n");

        // Summary
        if (endpoint.getSummary() != null && !endpoint.getSummary().isEmpty()) {
            sb.append("**Summary:** ").append(endpoint.getSummary()).append("\n\n");
        }

        // Description
        if (endpoint.getDescription() != null && !endpoint.getDescription().isEmpty()) {
            sb.append("**Description:** ").append(endpoint.getDescription()).append("\n\n");
        }

        // Operation ID
        if (endpoint.getOperationId() != null && !endpoint.getOperationId().isEmpty()) {
            sb.append("**Operation ID:** `").append(endpoint.getOperationId()).append("`\n\n");
        }

        // Consumes / Produces
        if (!endpoint.getConsumes().isEmpty()) {
            sb.append("**Consumes:** ").append(String.join(", ", endpoint.getConsumes())).append("\n\n");
        }
        if (!endpoint.getProduces().isEmpty()) {
            sb.append("**Produces:** ").append(String.join(", ", endpoint.getProduces())).append("\n\n");
        }

        // Parameters table
        formatParameters(sb, endpoint.getParameters());

        // Request Body
        if (endpoint.getRequestBodyType() != null && !endpoint.getRequestBodyType().isEmpty()) {
            sb.append("**Request Body:** `").append(endpoint.getRequestBodyType()).append("`\n\n");
            if (endpoint.getRequestBodyExample() != null && !endpoint.getRequestBodyExample().isEmpty()) {
                sb.append("```json\n").append(endpoint.getRequestBodyExample()).append("\n```\n\n");
            }
        }

        // Response
        if (endpoint.getResponseType() != null && !endpoint.getResponseType().isEmpty()) {
            sb.append("**Response:** `").append(endpoint.getResponseType()).append("`\n\n");
            if (endpoint.getResponseExample() != null && !endpoint.getResponseExample().isEmpty()) {
                sb.append("```json\n").append(endpoint.getResponseExample()).append("\n```\n\n");
            }
        }

        // cURL example
        sb.append("**Example Request:**\n\n");
        sb.append(generateCurlExample(endpoint));
        sb.append("\n");
    }

    private void formatParameters(StringBuilder sb, List<ParameterInfo> parameters) {
        if (parameters.isEmpty()) {
            return;
        }

        sb.append("**Parameters:**\n\n");
        sb.append("| Name | In | Type | Required | Description | Default | Example |\n");
        sb.append("|------|-----|------|----------|-------------|---------|--------|\n");

        for (ParameterInfo param : parameters) {
            sb.append("| ")
                    .append(escapeMarkdown(param.getName())).append(" | ")
                    .append(param.getIn() != null ? param.getIn() : "").append(" | ")
                    .append(param.getType() != null ? param.getType() : "").append(" | ")
                    .append(param.isRequired() ? "Yes" : "No").append(" | ")
                    .append(param.getDescription() != null ? escapeMarkdown(param.getDescription()) : "").append(" | ")
                    .append(param.getDefaultValue() != null ? escapeMarkdown(param.getDefaultValue()) : "").append(" | ")
                    .append(param.getExample() != null ? escapeMarkdown(param.getExample()) : "")
                    .append(" |\n");
        }
        sb.append("\n");
    }

    private String generateCurlExample(EndpointInfo endpoint) {
        StringBuilder curl = new StringBuilder();
        curl.append("```bash\ncurl -X ").append(endpoint.getHttpMethod());

        // Add headers
        curl.append(" \\\n  -H \"Content-Type: application/json\"");

        // Build URL with path parameters
        String url = "http://localhost:8080" + endpoint.getPath();
        curl.append(" \\\n  \"").append(url).append("\"");

        // Add query parameters
        List<ParameterInfo> queryParams = endpoint.getParameters().stream()
                .filter(p -> "query".equals(p.getIn()))
                .toList();
        for (ParameterInfo param : queryParams) {
            String exampleVal = param.getExample() != null ? param.getExample() : "value";
            curl.append(" \\\n  -d \"").append(param.getName()).append("=").append(exampleVal).append("\"");
        }

        // Add body for POST/PUT/PATCH
        if (("POST".equals(endpoint.getHttpMethod()) || "PUT".equals(endpoint.getHttpMethod())
                || "PATCH".equals(endpoint.getHttpMethod()))
                && endpoint.getRequestBodyExample() != null) {
            curl.append(" \\\n  -d '").append(endpoint.getRequestBodyExample().replace("'", "\\'")).append("'");
        }

        curl.append("\n```");
        return curl.toString();
    }

    private String escapeMarkdown(String text) {
        if (text == null) return "";
        return text.replace("|", "\\|")
                .replace("\n", " ");
    }

    private String toAnchor(String tag) {
        return tag.toLowerCase().replaceAll("[^a-z0-9]+", "-").replaceAll("^-|-$", "");
    }
}
